BurgerMvc/Controllers/OrderCustomerController.cs
using AutoMapper;
using BurgerMvc.BLL.AbstractServices;
using BurgerMvc.BLL.Dtos;
using BurgerMvc.DAL.Entities;
using BurgerMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace BurgerMvc.Controllers
{
    public class OrderCustomerController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IMapper _mapper;
        private readonly IOrderCustomerService _orderCustomerService;

        public OrderCustomerController(IOrderService orderService, IMapper mapper, IOrderCustomerService orderCustomerService)
        {
            _orderService = orderService;
            _mapper = mapper;
            _orderCustomerService = orderCustomerService;
        }

        public async Task<IActionResult> Index()
        {
            var menus = await _orderService.GetAllMenu();
            var allmenus = _mapper.Map<List<MenuItemViewModel>>(menus);
            var extras = await _orderService.GetAllExtra();
            var mapExtras = _mapper.Map<List<ExtraIngredientViewModel>>(extras);
            ViewBag.Extras = mapExtras;
            return View(allmenus);
        }
        public async Task<IActionResult> OrderCart()
        {
            var menus = await _orderService.GetAllMenu();
            var mappmenus = _mapper.Map<List<MenuItemViewModel>>(menus);
            ViewBag.Menus = mappmenus;

            var extras = await _orderService.GetAllExtra();
            var extra = _mapper.Map<List<ExtraIngredientViewModel>>(extras);
            ViewBag.Extras = extra;

            var orderactive = HttpContext.Session.GetInt32("OrderId");

            var ordersMenus = await _orderCustomerService.GetAllOrdersMenu();
            var menuwhere = ordersMenus.Where(x => x.OrderId == orderactive);
            ViewBag.OrdersMenus = _mapper.Map<List<OrdersMenuViewModel>>(menuwhere);

            var ordersExtras = await _orderCustomerService.GetAllOrdersExtra();
            var extraWhere = ordersExtras.Where(x => x.OrderId == orderactive);
            ViewBag.OrdersExtras = _mapper.Map<List<OrdersExtraViewModel>>(extraWhere);
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> OrderAdd()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> OrderAdd(OrderViewModel orderViewModel)
        {
            var order = _mapper.Map<OrderDto>(orderViewModel);
            var orderId = await _orderCustomerService.OrderAdd(order);
            if (orderId != 0)
            {
                HttpContext.Session.SetInt32("OrderId", orderId);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> OrdersMenuAdd(int menuId)
        {
            ViewBag.MenuId = menuId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> OrdersMenuAdd(OrdersMenuViewModel orderMenuViewModel)
        {
            var ordersMenu = _mapper.Map<OrdersMenuDto>(orderMenuViewModel);
            await _orderCustomerService.OrdersMenuAdd(ordersMenu);

            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> OrdersExtraAdd(int extraId)
        {
            ViewBag.ExtraId = extraId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> OrdersExtraAdd(OrdersExtraViewModel ordersExtraViewModel)
        {
            var ordersExtra = _mapper.Map<OrdersExtraDto>(ordersExtraViewModel);
            await _orderCustomerService.OrdersExtraAdd(ordersExtra);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> OrdersMenuDelete(int ordersMenuId)
        {
            await _orderCustomerService.OrdersMenuDelete(ordersMenuId);
            return RedirectToAction("OrderCart");
        }

        [HttpPost]
        public async Task<IActionResult> OrdersExtraDelete(int ordersExtraId)
        {
            await _orderCustomerService.OrdersExtraDelete(ordersExtraId);
            return RedirectToAction("OrderCart");
        }

        [HttpGet]
        public async Task<IActionResult> OrderUpdate(int orderId, decimal total)
        {
            ViewBag.Total = total;
            var orders = await _orderCustomerService.GetAllOrder();
            var order = orders.FirstOrDefault(x => x.Id == orderId);
            var ordermap = _mapper.Map<OrderViewModel>(order);
            return View(ordermap);
        }

        [HttpPost]
        public async Task<IActionResult> OrderUpdate(int orderId, OrderDto orderDto)
        {
            await _orderCustomerService.OrderUpdateTotal(orderId, orderDto);
            HttpContext.Session.Remove("OrderId");

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetByOrdersForUser()
        {
            var userlogin = HttpContext.Session.GetInt32("UserId");

            var orders = await _orderCustomerService.GetAllOrder();
            var order = orders.Where(x => x.IsOrderConfirmed == true && x.UserId == userlogin).OrderByDescending(x=>x.ModifiedDate);
            var ordermap = _mapper.Map<List<OrderViewModel>>(order);
            return View(ordermap);
        }

        [HttpGet]
        public async Task<IActionResult> OrderDetail(int orderId)
        {
            var ordersMenus = await _orderCustomerService.GetAllOrdersMenu();
            var orderMenus =  ordersMenus.Where(x=>x.OrderId== orderId).ToList();
            var mapOrderMenus = _mapper.Map<List<OrdersMenuViewModel>>(orderMenus);
            ViewBag.Ordersmenus = mapOrderMenus;

            var ordersExtras = await _orderCustomerService.GetAllOrdersExtra();
            var orderExtras = ordersExtras.Where(x=>x.OrderId==orderId).ToList();
            var mapOrderExtras = _mapper.Map<List<OrdersExtraViewModel>>(orderExtras);
            ViewBag.Ordersextras = mapOrderExtras;

            var menus = await _orderService.GetAllMenu();            
            var mappMenus = _mapper.Map<List<MenuItemViewModel>>(menus);
            ViewBag.Menus = mappMenus;

            var extras = await _orderService.GetAllExtra();
            var mapExtras = _mapper.Map<List<ExtraIngredientViewModel>>(extras);
            ViewBag.Extras = mapExtras;
            return View();
        }
    }
}

BurgerMvc/Views/OrderCustomer/GetByOrdersForUser.cshtml
@model List<OrderViewModel>

<div class="row">
    <div class="col-md-12">
        <div class="card p-4 mb-4" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
            <h1>
                Siparişler
            </h1>
        </div>
        @foreach (var item in Model)
        {
            <div class="card p-4 mb-4" style="background-color:ivory ;border-block-color:black; border-radius:24px; text-align:center;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-body">
                            <h5 class="card-title">Sipariş Tarihi: @item.ModifiedDate</h5>
                            <p class="card-text">Toplam Fiyat: @item.TotalPrice</p>

                            <form asp-action="OrderDetail" method="get" style="display:inline">
                                <input type="hidden" name="orderId" value="@item.Id" />
                                <button type="submit" class="btn btn-success"><i class="">Detaylar</i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

BurgerMvc/Views/OrderCustomer/Index.cshtml
@model List<MenuItemViewModel>
@{
    var extras = ViewBag.Extras as List<ExtraIngredientViewModel>;
    var orderactive = Context.Session.GetString("OrderId");

}
<div class="row">
    <div class="col-md-6">
        <div class="card p-4 mb-4" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
            <h1>
                MENÜLER
            </h1>
        </div>
        @foreach (var item in Model)
        {
            <div class="card  p-4 mb-4" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="~/Images/@item.Photo" class="img-fluid rounded-start" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">@item.Title</h5>
                            <p class="card-text">@item.Content</p>
                            <p class="card-text">@item.Price</p>
                            @if (orderactive != null)
                            {
                                <form asp-action="OrdersMenuAdd" method="get" style="display:inline">
                                    <input type="hidden" name="menuId" value="@item.Id" />
                                    <input type="hidden" name="price" value="@item.Price" />
                                    <button type="submit" class="btn btn-success"><i class="bi bi-basket2"></i></button>
                                </form>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-6">
        <div class="card p-4 mb-4" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
            <h1>
                EKSTRA MALZEMELER
            </h1>
        </div>
        @foreach (var item in extras)
        {
            <div class="card  p-4 mb-4" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="~/Images/@item.Photo" class="img-fluid rounded-start" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">@item.Name</h5>
                            <p class="card-text">@item.Price</p>
                            <p class="card-text">@item.Photo</p>
                            @if (orderactive != null)
                            {
                                <form asp-action="OrdersExtraAdd" method="get" style="display:inline">
                                    <input type="hidden" name="extraId" value="@item.Id" />
                                    <button type="submit" class="btn btn-success"><i class="bi bi-basket2"></i></button>
                                </form>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

BurgerMvc/Views/OrderCustomer/OrderAdd.cshtml
@model OrderViewModel
@{
    var UserLoginId = Context.Session.GetInt32("UserId");
}
<script>
    window.onload = function () {
        // Formu otomatik olarak gönder
        document.getElementById('orderForm').submit();
    };
</script>

<form id="orderForm" asp-controller="OrderCustomer" asp-action="OrderAdd" method="post" enctype="multipart/form-data" class="form-control">
    <div class="form-group">
        <input type="hidden" id="UserId" name="UserId" value="@UserLoginId" />
    </div>
    <div class="form-group m-2">
        <!-- Butonu gizlemek için inline CSS kullanıyoruz -->
        <button type="submit" class="btn btn-primary" style="display: none;">Sipariş Ver</button>
    </div>
</form>

BurgerMvc/Views/OrderCustomer/OrderCart.cshtml
@{
    var allmenus = ViewBag.Menus as List<MenuItemViewModel>;
    var allOrderMenus = ViewBag.OrdersMenus as List<OrdersMenuViewModel>;
    var allextras = ViewBag.Extras as List<ExtraIngredientViewModel>;
    var allOrderExtras = ViewBag.OrdersExtras as List<OrdersExtraViewModel>;
    decimal total = 0m;
    decimal big = 50m;
    decimal middle = 20m;
    var orderactive = Context.Session.GetInt32("OrderId");
}

<div class="row">
    <div class="col-md-5">
        <div class="card p-2 mb-2" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
            <h2>
                MENÜLER
            </h2>
        </div>
        @foreach (var item in allmenus)
        {
            foreach (var item2 in allOrderMenus)
            {
                if (item2.MenuItemId == item.Id)
                {
                    <div class="col-12">
                        <div class="card p-2 mb-2" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <img src="~/Images/@item.Photo" class="img-fluid rounded-start" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">@item.Title</h5>
                                        <p class="card-text">@item.Content</p>
                                        <p class="card-text">Fiyat: @item.Price</p>
                                        <p class="card-text">Miktar: @item2.Quantity</p>
                                        <p class="card-text">Boyut: @item2.Size</p>

                                        <form asp-action="OrdersMenuDelete" method="post" style="display:inline">
                                            <input type="hidden" name="ordersMenuId" value="@item2.Id" />
                                            <button type="submit" class="btn btn-danger"><i class="bi bi-trash"></i></button>
                                        </form>
                                        @{
                                            if (item2.Size == BurgerMvc.BLL.Dtos.Size.Küçük)
                                            { total += item.Price * item2.Quantity; }
                                            if (item2.Size == BurgerMvc.BLL.Dtos.Size.Orta)
                                            { total += (item.Price * item2.Quantity) + (middle * item2.Quantity); }
                                            if (item2.Size == BurgerMvc.BLL.Dtos.Size.Büyük)
                                            { total += (item.Price * item2.Quantity) + (big * item2.Quantity); }
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        }
    </div>
    <div class="col-md-5">
        <div class="card p-2 mb-2" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
            <h2>
                EKSTRA MALZEMELER
            </h2>
        </div>
        @foreach (var item in allextras)
        {
            foreach (var item2 in allOrderExtras)
            {
                if (item2.ExtraIngredientId == item.Id)
                {
                    <div class="col-12">
                        <div class="card p-2 mb-2" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <img src="~/Images/@item.Photo" class="img-fluid rounded-start" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">@item.Name</h5>
                                        <p class="card-text">Fiyat: @item.Price</p>
                                        <p class="card-text">Miktar: @item2.Quantity</p>

                                        <form asp-action="OrdersExtraDelete" method="post" style="display:inline">
                                            <input type="hidden" name="ordersExtraId" value="@item2.Id" />
                                            <button type="submit" class="btn btn-danger"><i class="bi bi-trash"></i></button>
                                        </form>
                                        @{
                                            total += item.Price * item2.Quantity;
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        }
    </div>
    <div class="col-md-2">
        <div class="col-12">
            <div class="card p-2 mb-2" style="background-color:yellowgreen ;border-block-color:black; border-radius:24px;text-align:center;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <h3>Toplam Fiyat @total</h3>
                        <form asp-action="OrderUpdate" method="get" style="display:inline">
                            <input type="hidden" name="orderId" value="@orderactive" />
                            <input type="hidden" name="total" value="@total.ToString(System.Globalization.CultureInfo.InvariantCulture)" />
                            @if (total == 0)
                            {
                                <div class="alert alert-danger">Henüz sipariş vermediniz.</div>
                            }
                            else{
                            <button type="submit" class="btn btn-success"><i class="btn btn-primary">Onayla</i></button>
                            }
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BurgerMvc/Views/OrderCustomer/OrderDetail.cshtml
@{
    var ordersmenus = ViewBag.Ordersmenus as List<OrdersMenuViewModel>;
    var ordersextra = ViewBag.Ordersextras as List<OrdersExtraViewModel>;
    var menus = ViewBag.Menus as List<MenuItemViewModel>;
    var extras = ViewBag.Extras as List<ExtraIngredientViewModel>;
}
<div class="row">
    <div class="col-md-6">
        <div class="card p-2 mb-2" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
            <h2>
                MENÜLER
            </h2>
        </div>
        @foreach (var item in ordersmenus)
        {
            foreach (var item2 in menus)
            {
                if (item.MenuItemId == item2.Id)
                {
                    <div class="col-12">
                        <div class="card p-2 mb-2" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <img src="~/Images/@item2.Photo" class="img-fluid rounded-start" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">@item2.Title</h5>
                                        <p class="card-text">@item2.Content</p>
                                        <p class="card-text">Fiyat: @item2.Price</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        }
    </div>
    <div class="col-md-6">
        <div class="card p-2 mb-2" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
            <h2>
                EKSTRA MALZEMELER
            </h2>
        </div>
        @foreach (var item in ordersextra)
        {
            foreach (var item2 in extras)
            {
                if (item.ExtraIngredientId == item2.Id)
                {
                    <div class="col-12">
                        <div class="card p-2 mb-2" style="background-color:ivory ;border-block-color:black; border-radius:24px;text-align:center;">
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <img src="~/Images/@item2.Photo" class="img-fluid rounded-start" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">@item2.Name</h5>
                                        <p class="card-text">Fiyat: @item2.Price</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        }
    </div>
</div>

BurgerMvc/Views/OrderCustomer/OrderUpdate.cshtml
@model OrderViewModel

@{
    var Total = ViewBag.Total;
}
<script>
    window.onload = function () {
        // Formu otomatik olarak gönder
        document.getElementById('orderForm').submit();
    };
</script>

<form id="orderForm" asp-controller="OrderCustomer" asp-action="OrderUpdate" method="post" enctype="multipart/form-data" class="form-control">
    <div class="form-group">

        <input type="text" class="form-control" id="orderId" name="orderId" required value="@Model.Id" hidden />
    </div>
    <div class="form-group">

        <input type="text" class="form-control" id="TotalPrice" name="TotalPrice" required value="@Total" hidden />
    </div>
    <div class="form-group">

        <input type="text" class="form-control" id="IsOrderConfirmed" name="IsOrderConfirmed" required value="True" hidden />
    </div>  
    <div class="form-group m-2">
        <!-- Butonu gizlemek için inline CSS kullanıyoruz -->
        <button type="submit" class="btn btn-primary" style="display: none;">Onay</button>
    </div>
</form>

BurgerMvc/Views/OrderCustomer/OrdersExtraAdd.cshtml
@model OrdersExtraViewModel
@{
    var orderactive = Context.Session.GetInt32("OrderId");

    var extraId = ViewBag.ExtraId;
}
<form asp-controller="OrderCustomer" asp-action="OrdersExtraAdd" method="post" enctype="multipart/form-data" class="form-control">
    <div class="form-group">
        <input type="hidden" id="OrderId" name="OrderId" value="@orderactive" />
    </div>
    <div class="form-group">
        <input type="hidden" id="ExtraIngredientId" name="ExtraIngredientId" value="@extraId" />
    </div>
    <div class="form-group">
        <label for="Quantity">Quantity</label>
        <input type="number" class="form-control" id="Quantity" name="Quantity" value="1" min="1">
    </div>

    <div class="form-group m-2">
        <button type="submit" class="btn btn-primary">Siparişe Ekstra Ekle</button>
    </div>
</form>

BurgerMvc/Views/OrderCustomer/OrdersMenuAdd.cshtml
@using BurgerMvc.Models.Enum
@model OrdersMenuViewModel

@{
    var orderactive = Context.Session.GetInt32("OrderId");
    var menuId = ViewBag.MenuId;
}

<form asp-controller="OrderCustomer" asp-action="OrdersMenuAdd" method="post" enctype="multipart/form-data" class="form-control">

    <div class="form-group">
        <input type="hidden" id="OrderId" name="OrderId" value="@orderactive" />
    </div>
    <div class="form-group">
        <input type="hidden" id="MenuItemId" name="MenuItemId" value="@menuId" />
    </div>
    <div class="form-group">
        <label for="Quantity">Miktar</label>
        <input type="number" class="form-control" id="Quantity" name="Quantity" value="1" min="1">
    </div>
    <div class="form-group">
        <label for="Size">Boyut Seçiniz</label>
        <select class="form-control" id="Size" name="Size">
            @foreach (var item in Enum.GetValues(typeof(Size)))
            {
                <option value="@((int)item)">
                    @item.ToString()
                </option>
            }
        </select>
    </div>
    <div class="form-group">
        <h5 class="alert alert-danger text-danger"> 20 TL fark ile Orta boy veya 50 TL fark ile Büyük boy almak isterseniz boyut değiştirebilirsiniz!!!</h5>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Siparişe Menu Ekle</button>
    </div>

</form>